### ISSUE TITLE
Turkle as an importable app

### ISSUE THREAD

**Issue by TomLippincott** [hltcoe/turkle#100]
@vandurme @cash @charman 

Things are going great with the library managing their own instance for humanists.  The next step on that end is to tie it in with the visualization and ML system (also Django-based).  Are there reasons not to:

* turn imports like `turkle.models` into relative imports like `.models`
* move to a more recent version of Django (e.g. 3.1.2)
* add the functionality to install as a package

These seem straightforward, with the exception of Django version (looks like an intentional decision, since JSONField functionality is now built in).

I can do this myself, just want to see if there are particular blockers before starting.

**Comment by cash** [comment]
@TomLippincott I made a PR to use relative imports.

Turkle started with Django 1. We upgrade to Django 2 this summer. Upgrading to 3 starts by checking dependencies. I don't know if we have a reason to not upgrade. @charman and I haven't discussed.

We should talk more about plans.

**Comment by TomLippincott** [comment]
Sounds great!

In the meantime, I've started a 'packaging' branch that bumps Django to 3.1.2 and adds the metadata allowing it to be installed as a package (and then included in a site's "INSTALLED_APPS" setting).  It's functional, but needs plenty of cleanup: I'll keep picking away at it over the next month or so.
