### ISSUE TITLE
Add a page for requesters to determine who has assignments

### ISSUE THREAD

**Issue by cash** [hltcoe/turkle#114]
Maybe add this as a new module in the admin backend. Admin would click the link and go to a page where they can select a batch and then a table with the incomplete assignments (assigned but not complete). They would want to see date assigned, date expired, and name/email of the worker.

Alternatively, there could be a link on the batch table to see incomplete assignments. The batch table page is already really busy so I prefer the first option.

**Comment by charman** [comment]
@cash - What about adding the table of incomplete assignments to the Batch Stats page? The Batch Stats page already provides granular information about which users have completed assignments from a Batch.

**Comment by cash** [comment]
That would work. I've been asked a few times for this information and have had to manually pull it from the database.

I think at some point as we add more and more capability to the admin backend we will need to do a UI overhaul for it....but the batch stats page is probable the best place to put it if we don't want to create a new pages.
