### ISSUE TITLE
Add page that lets admins view a particular user's stats

### ISSUE THREAD

**Issue by cash** [hltcoe/turkle#115]

**Comment by charman** [comment]
Turkle currently has a User Stats page that is only accessible to the user while they are logged in. The page looks like:

<img width="1133" alt="Screen Shot 2021-04-07 at 9 49 41 AM" src="https://user-images.githubusercontent.com/424563/113877714-f793c300-9786-11eb-8679-68e90e4da782.png">

The statistics on this page can be filtered by date range using a form. The form generates a GET request that reloads the page.

The user stats page includes a table that breaks down progress at the Batch and Project level, where Batch-level stats are grouped under Project-level stats.

@cash - What information and functionality were you looking for in the initial admin-visible User Stats page?

**Comment by cash** [comment]
This came to me as a request during a meeting about the SCALE annotation tasks or maybe it was from a discussion with @paulmcnamee. I believe the purpose was to check on the progress of a particular annotator - maybe someone new - maybe to make sure they are working on the tasks that you want them to work on. Right now, administrators can only see work by an annotator on one batch at a time.

I think the easiest way to implement this is to change the URL so that the user's username is a parameter. Make sure permissions on the page only allow that user or an administrator to see it. And then add a stats column to the user page in the admin backend.

This is all assuming that the current user stats page has what the administrators want. I should have taken more detail notes at the time.
