### ISSUE TITLE
Error due to missing trailing comma 

### ISSUE THREAD

**Issue by TomLippincott** [hltcoe/turkle#14]
The TEMPLATE_DIRS variable in turkle/settings.py needs a comma after its one item, to ensure that it's interpreted as a tuple: otherwise manage.py throws an error.

**Comment by cash** [comment]
TEMPLATE_DIRS should be a list so switching to [] should solve that issue. That variable is also deprecated since Django 1.8 so updating Turkle to support a newer Django should switch to setting DIRS.

**Comment by TomLippincott** [comment]
Gotcha: speaking of later versions, I opened a ticket on that, too.  It might just be a matter of updating the README to whatever is used to populate the database now, rather than syncdb.

**Comment by cjmay** [comment]
This should be closed.
