### ISSUE TITLE
Template namespace clashes

### ISSUE THREAD

**Issue by TomLippincott** [hltcoe/turkle#177]
Turkle currently has templates outside the conventional project namespacing, e.g. `turkle/templates/index.html`, which means to override this template one must use `myproject/templates/index.html`.  The idiom is to place templates like `turkle/templates/turkle/index.html` to allow targeted overriding of templates without clashes between projects/apps.

**Comment by cash** [comment]
@TomLippincott I agree that the templates in the templates directory (base.html to task_base.html) should be moved under a new `templates/turkle` directory. The registration directory should stay there as it is overriding templates from contrib.auth. I believe the admin directory should also stay as-is (though at some point, we might want to update the location of the stats templates).
