### ISSUE TITLE
Increase template size limit on hltcoe.turkle.org

### ISSUE THREAD

**Issue by ccmaymay** [hltcoe/turkle#202]
Could we please increase the template size limit on hltcoe.turkle.org?  2 MB or greater would work for me now, but I would suggest 10 MB or even 100 MB to be safe.  I have a ~1.2 MB template compiled from Vue that I would like to use on Turkle.  I'm looking into minification right now, but even if I can get that to work with my build, it will only just barely bring the file under the current 1 MB limit.

I believe this is reasonable, as the default data upload size is 100 MB, and there are at least an order of magnitude more data uploads than templates.

**Comment by cash** [comment]
@ccmaymay Please reach out to @charman about this as he maintains that site.

General question for anyone reading this: I think we set the default to 64 KB for a stock install of Turkle. Any reason to not raise this and what should we raise it to?

**Comment by ccmaymay** [comment]
@cash @charman how doable would this change be?

**Comment by charman** [comment]
@ccmaymay - I have increased the template size limit on hltcoe.turkle.org from 1MB to 10MB.

**Comment by ccmaymay** [comment]
Thanks @charman!  I got an HTTP 500 when trying to create the project just now—do you know what happened?

**Comment by ccmaymay** [comment]
I tried again (twice), same error... it seems to be giving me the silent treatment.

**Comment by cash** [comment]
The wait_timeout or max_allowed_packet might have to be adjusted in the mysqld configuration for MySQL to handle a multiple MB insert.
