### ISSUE TITLE
Compatiliby with AMT Crowd HTML Elements 

### ISSUE THREAD

**Issue by danyaljj** [hltcoe/turkle#205]
@cash is Turkle compatible with [`crowd-html-elements.js`](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_HTMLCustomElementsArticle.html) library?  

```
<script src="https://assets.crowd.aws/crowd-html-elements.js"></script>
```

**Comment by danyaljj** [comment]
Just saw #42 from which it seems that we'd need to write some additional JS code to make it work for Turkle.

**Comment by cash** [comment]
@danyaljj Yes, it would be great if that just worked out of the box! I haven't had time to look into it in any more detail, but I think it should be possible.

**Comment by danyaljj** [comment]
I did a bit of digging and found out that the action of the submission form is set inside [`crowd-html-elements-without-ce-polyfill.js`](https://assets.crowd.aws/crowd-html-elements-without-ce-polyfill.js) which itself is loaded by [`crowd-html-elements.js`](https://assets.crowd.aws/crowd-html-elements.js). So I can make a copy of these scripts and tweak them. 


Specifically this segment of `crowd-html-elements-without-ce-polyfill.js` seems to be setting the form action: 

```javascript
            _setupFormForMturk(e) {
                e.host.match(/\.sagemaker\.aws$/) && (this._crowdScaleSubmissionEndpoint = e.origin,
                this.answerFormat = null);
                var t = new URLSearchParams(e.search)
                  , o = V._validateEndpoint(t.get("turkSubmitTo"));
                this.form.method = "post",
                this.form.action = "".concat(o, "/mturk/externalSubmit"),
                this._mturkParams = {
                    assignmentId: t.get("assignmentId"),
                    workerId: t.get("workerId")
                }
            }
```

Though I am not sure what is the right change here. Following the example [here](https://github.com/hltcoe/turkle/blob/master/docs/TEMPLATE-GUIDE.rst#how-turkle-renders-templates), I tried: 

 - dropping `this.form.action = "".concat(o, "/mturk/externalSubmit"),` but the submissions ended up getting redirected to `/null`.  See the picture below: 
 <img width="2044" alt="Screen Shot 2023-08-24 at 2 32 28 AM" src="https://github.com/hltcoe/turkle/assets/2441454/d624f0b7-afdf-4337-ad9e-3920a618c06f">

- adding `this.form.name = "mturk_form", this.form.id = "mturk_form", this.form.target="_parent"` which didn't seem to change the behavior. 

If you happen to have any suggestions for me, please let me know.

**Comment by danyaljj** [comment]
**Update:** so my conclusion thus far is that, making AMT default element work for Turkle is a waste of time. 
The default elements create their own "submit" button (and Turkle adds its own submit button). Modifying the "click" event of this button (e.g., making removing it or copying its payload) is non-trivial.
