### ISSUE TITLE
 csv.field_size_limit(sys.maxsize) (Python int too large to convert to C long)

### ISSUE THREAD

**Issue by fsysean** [hltcoe/turkle#31]
Resolved in https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072

**Comment by charman** [comment]
@fsysean - Thanks for reporting this!  Will fix.

Out of curiosity, what OS and Python distribution are you using?

**Comment by fsysean** [comment]
OS: edition Windows 10 Enterprise 64 Version： 1803
python： Python 3.7.1

**Comment by charman** [comment]
Thanks!  How did you install Python?  Are you using the Anaconda distribution, the version from Python.org, or some other source?

**Comment by fsysean** [comment]
I use Anaconda.

**Comment by charman** [comment]
Thanks for reporting this!

Fixed in https://github.com/hltcoe/turkle/commit/211d7d989df34588fbef47b7ef33415d107f6108
