### ISSUE TITLE
Button "Save and add another" user does not work

### ISSUE THREAD

**Issue by bricksdont** [hltcoe/turkle#33]
While creating a new user in the GUI, after filling in all relevant fields, clicking

<kbd>Save and add another</kbd>

does not work as intended. It takes you back to the overview of all users, instead of opening an empty form for a new user, as I was expecting.

**Comment by cash** [comment]
I've fixed this. The master branch has the change. It would be great if you could confirm that the change works for you.

**Comment by bricksdont** [comment]
Thanks Cash! I am reluctant to test this in our live system right now because we are currently running an important evaluation. Updating live code to master has a chance of breaking things, right?

Still, will test as soon as I can.

**Comment by bricksdont** [comment]
Just tested with current master and a dummy server on localhost: works fine. Closing
