### ISSUE TITLE
Creating a new user: fields are pre-populated

### ISSUE THREAD

**Issue by bricksdont** [hltcoe/turkle#34]
While creating a new user with the GUI, annoyingly, the user name and password field are pre-populated with my own username and password.

Also, after clicking <kbd>Save</kbd>, my browser asks me to update my stored credentials, which is also annoying.

I don't know enough to know if 1) this is a problem with my browser settings or 2) a bug on Turkle's side.

Could you please clarify? Thanks so much.

**Comment by charman** [comment]
@bricksdont - This is a problem with your browser settings.  Turkle does not pre-populate these fields.

**Comment by cash** [comment]
It might be possible to override this behavior. See this very long and partly depressing thread: https://gist.github.com/niksumeiko/360164708c3b326bd1c8

**Comment by cash** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by bricksdont** [comment]
Does this mean that in the HTML that Turkle serves you could use e.g.

    autocomplete="new-password"

and some browsers would respect that?

**Comment by cash** [comment]
I think so. We should definitely try that because having the browser auto populate the fields is very annoying.

**Comment by cash** [comment]
Looks like once a browser remembers a username/password for a site, it is difficult to prevent it from autofilling.  

I added a custom user creation form:
```
class CustomUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['autocomplete'] = 'new-password'
        self.fields['password1'].widget.attrs['autocomplete'] = 'new-password'
```
and hooked that up to the user admin:

```
class CustomUserAdmin(UserAdmin):
    add_form = CustomUserCreationForm
```

No change on Firefox behavior even though the autocomplete attribute is set. Everything that I've read says you need to either rename the fields or use read-only when the page loads.
