### ISSUE TITLE
Allow users to view contributions

### ISSUE THREAD

**Issue by mjpost** [hltcoe/turkle#38]
It would be helpful if users had access to a page where they could see how information such as how much time they'd spent on the system, how many tasks they'd done, and so on, perhaps broken down by week or month.

**Comment by charman** [comment]
This is already implemented in the master branch.  There is now a "Stats" button on the top-right corner of the UI that allows users to view the number of tasks they have completed and the time elapsed working on these tasks.  These numbers are broken down both by Project and by Batch.  The default view displays statistics on all tasks the user has ever worked on, but there are two date-pickers that allow users to select a custom range for the report.

**Comment by mjpost** [comment]
Any thoughts on what the effect would be of updating a live system from commit c8e9ed3a04ea86bae2ecad185073b93815c6283b? (I'm not inclined to do it...)

**Comment by mjpost** [comment]
Hmm, this commit seems not to exist any more. It was from Sunday, March 3.

**Comment by charman** [comment]
There have been no changes to the database schema, so updating and then reverting won't affect any data you have collected.

The code that we use for updating the size of the iframe has changed.  The size of the iframe may not look correct until browsers force-reload the browser cache (e.g. Command-Shift-R).

How are you ascertaining that the commit no longer exists?  As best I can tell, it still exists.

**Comment by mjpost** [comment]
Oh, you're right. I perused the commit history and couldn't find it, but I see the link resolves.

**Comment by cash** [comment]
@charman what commit are you running on production?

**Comment by cash** [comment]
@mjpost I think you should be save updating to 5c7a69215f3db7a37a1160df9a32b944a088a028

As @charman said, there have been no database schema changes, but after that commit we merged in some layout/CSS changes that need more testing on multiple browsers to see how browser caching affects rendering.

**Comment by mjpost** [comment]
Okay, great, thanks.

**Comment by charman** [comment]
@mjpost - You may also need to manually update your `turkle_site/settings.py` file.  The version of this file in the `master` branch is configured to use SQLite, but your version of this file is customized to use MySQL.

**Comment by cash** [comment]
I believe we have added one setting: TURKLE_TEMPLATE_LIMIT
To better match Mechanical Turk, we have a default limit of template size of 64 KB. If you want more than that, set this in your settings.py to something larger:

```
TURKLE_TEMPLATE_LIMIT = 1024
```

This would be a 1 MB limit as value is in KB

**Comment by mjpost** [comment]
Hmm, updating this did in fact break our system. A "Submit" button was not visible at the end of a long HIT.

**Comment by mjpost** [comment]
Just FYI. Even with the 5c7a692 commit, there seemed to be some iframe issues.

**Comment by cash** [comment]
Do you have any screen shots of the issues (you can send directly to me if you don't want to post here)? Any information on browsers would also be useful.

**Comment by cash** [comment]
On a different thread, we have figured out the issue with the missing submit button (the button was floated so the JavaScript iframe code wasn't including it size calculations).

I'm closing this as release 2.1.0 has the new Stats page for workers. If that is missing information, please open a new issue.
