### ISSUE TITLE
`--insecure` as a hard-coded option

### ISSUE THREAD

**Issue by bricksdont** [hltcoe/turkle#40]
Turkle's `manage.py` hardcodes using `--insecure` for the `runserver` command:

https://github.com/hltcoe/turkle/blob/master/manage.py#L26

Which means that static files are served even if not in debug mode, right? Why is that?

Thanks so much for your help.

**Comment by cash** [comment]
That file is only used when using the development server. Instructions for production here: https://github.com/hltcoe/turkle/blob/master/docs/ADMINISTRATION.md

In production, the manage.py script is not used.

**Comment by bricksdont** [comment]
Thanks! Closing.
