### ISSUE TITLE
How to access worker's data from turkle folder?

### ISSUE THREAD

**Issue by mfayoub** [hltcoe/turkle#41]
I wanted to access the annotations done by workers through the turkle folder. This is useful in case if the server has any issues and prevented me from downloading the results. So is there any way to do so ? Are results saved inside db.sqlite3 ?

**Comment by charman** [comment]
If you are using the default settings for Turkle, then Turkle will use the SQLite database backend, and all worker data will be stored in the file `db.sqlite3` in the Turkle home directory.

**Comment by mfayoub** [comment]
Great thanks for your reply!
