### ISSUE TITLE
HIT template reload

### ISSUE THREAD

**Issue by cjmay** [hltcoe/turkle#45]
I'm using Turkle for development, and it would be *extremely* helpful to me if there was an easy way to "reload" the HIT template for a batch.  That is, I'm recreating a project + batch every time I want to check the template, a multi-step process; if I could instead sync the template for a batch to a file on disk, it would make my development cycle *much* faster.  (It would help if there were just a "reload" button or script to press, but I could even imagine logic going in the view to re-read a specified file from disk every time.)

This would definitely add complexity, and I don't know if anyone does, or ever would, use Turkle in a similar way to how I'm using it, so this might not be worth the costs.  And maybe there's a better way to develop HIT templates that I just haven't realized?

Thanks :)

**Comment by charman** [comment]
Prototurk is intended to make the HIT development process as easy as possible:

https://github.com/hltcoe/prototurk

Prototurk reloads both the HTML template and CSV file with every browser refresh.

**Comment by cjmay** [comment]
Oh fantastic, thanks so much!  That looks perfect.
