### ISSUE TITLE
sign up option

### ISSUE THREAD

**Issue by noetits** [hltcoe/turkle#46]
Hello,

Is there an option to make people sign up themselves and then access the actives batches ?

In fact I would like to ask some people to a listening test by sending them a link from which they could do it. Something like a google form with audio samples.

But in turkle, an account has to be created for each of them before by an admin. Except if there is a way to put a sign up option and then they would do the test.

There is also the option of not using the login. But then I cannot make each people to do a list of questions.

Thanks

**Comment by cash** [comment]
We're releasing a version of Turkle soon that is an app that a site can be built on by including additional apps. This will provide a lot more flexibility in how people set up their site. 

I just tried this with the django-user-accounts app and got self sign up to work. Here is the basics with a clean django site using Turkle as an app:

1. install django-user-accounts
2. add "django.contrib.sites" and "account" to your installed apps
3. add "account.context_processors.account" to your context processors
4. install as normal with migrate
5. create a site object using the django shell
6. add the urls of the account app to your urls: path("account/", include("account.urls"))
7. re-register some urls to match the nicknames Turkle uses for routes. Turkle uses "login" and they use "account_login" so their urls will need to be registered with our shorter names. 
8. implement all the templates that the account app expects*

Documentation on the django-user-accounts app here: https://django-user-accounts.readthedocs.io/en/latest/
Anyone wishing to try this should read through its documentation.

*The people behind django-user-accounts have some demo templates at https://github.com/pinax/pinax-templates/tree/master/pinax/templates/templates/account

I expect that it is a few hours of work if a person knows django to get this working completely. I was able to get a mostly working version in 30 minutes with only some issues with the templates. Getting all the templates working would take longer and I was only doing it as a demonstration.

If anyone wanted to make this easier through an app that included re-registered urls and templates, I would be willing to provide some direction. For now, I'm going to close this as we don't have current plans to integrate self registration directly into Turkle.
