### ISSUE TITLE
Update Travis CI to run all tests run by GitLab CI

### ISSUE THREAD

**Issue by charman** [hltcoe/turkle#87]
The Travis CI pipeline currently only builds one of the Docker images, while the GitLab CI pipeline builds both Docker images, runs the integrated test suite, runs style checks using flake8, and builds the documentation.

**Comment by cash** [comment]
@charman I can work on this today.

**Comment by cash** [comment]
I'm looking at using Github Actions instead

**Comment by charman** [comment]
I'm unfamiliar with GitHub Actions, but also have minimal experience with Travis.  Feel free to switch to whichever CI runner you think is best.

**Comment by cash** [comment]
They both seem equally annoying to configure for something complicated.
