### ISSUE TITLE
MySQL support in docker hub image

### ISSUE THREAD

**Issue by markpatton** [hltcoe/turkle#90]
There is a Dockerfile with MySQL support and a Dockerfile without. The one without is used to build the docker hub image hltcoe/turkle:latest. 

We need to determine if we should be deploying in production with MySQL or without. If we want MySQL, then docker hub should have an image with MySQL support to ease deployment.

**Comment by cash** [comment]
Confirmed that we are not pushing the image with MySQL to docker hub. @charman do you know if this was an oversight or intentional?

**Comment by charman** [comment]
This was an oversight.

**Comment by charman** [comment]
@markpatton - If you are deploying Turkle in production you could use another Django-supported production relational database like PostgreSQL, MariaDB or Oracle. But you should definitely not use SQLite as the relational database on a production server. 

Per the Turkle [Administration Guide](https://turkle.readthedocs.io/en/latest/ADMINISTRATION.html):

> While Turkle can run out of the box using the Django development web server and a SQLite database, we recommend using a scalable database and a production quality WSGI HTTP server.

**Comment by charman** [comment]
I have update the Docker Hub configuration for the `hltcoe/turkle` image to build Docker images from both `Dockerfile` and `Dockerfile-MySQL`.

`Dockerfile` is used to generate images tagged `latest` (from the master branch) and `release-{sourceref}` (for commits tagged with a numeric version number).

`Dockerfile-MySQL` is used to generate images tagged `latest-MySQL` (from the master branch) and `release-{sourceref}-MySQL` (for commits tagged with a numeric version number).

https://hub.docker.com/r/hltcoe/turkle/tags
