### ISSUE TITLE
relative links not clickable in Github readme

### ISSUE THREAD

**Issue by cash** [hltcoe/turkle#92]
The readme is used for readthedocs so the links are created to work with sphinx. The main readme in the docs folder is a symbolic link to the one in the root of the repository.

**Comment by charman** [comment]
I don't think we're actually linking to the readthedocs documentation (https://turkle.readthedocs.io/) from anywhere right now. One option would be to move the current root-level `README.rst` into `docs/` (getting rid of the symbolic link), and add a new, shorter root-level README that directs people to readthedocs.

**Comment by charman** [comment]
The README file is also displayed on the Docker Hub page for the `hltcoe/turkle` Docker image:

https://hub.docker.com/r/hltcoe/turkle

The relative links are (also) not clickable on this Docker Hub page.
