### ISSUE TITLE
Release Turkle 2.2.0

### ISSUE THREAD

**Issue by charman** [hltcoe/turkle#93]

**Comment by charman** [comment]
@cash - Were there any additional changes you wanted to see before we released Turkle 2.2.0?

**Comment by cash** [comment]
no, looks good for release

**Comment by charman** [comment]
I've pushed the 2.2.0 tag.

Versioned documentation is available on readthedocs (and I updated the GitHub repo information to link to readthedocs);

https://turkle.readthedocs.io/en/2.2.0/

Docker images tagged `release-2.2.0` and `release-2.2.0-MySQL` are now available on Docker Hub:

https://hub.docker.com/r/hltcoe/turkle/tags
