### ISSUE TITLE
Update "preview" view to provide stronger visual signal not to work on task

### ISSUE THREAD

**Issue by charman** [hltcoe/turkle#94]
New users will frequently spend time working on a task in the "preview" view only to discover that their annotation efforts were wasted when they try to submit their work.

The preview view currently displays the task template with a "gray tint" (by setting the opacity of the iframe to 0.8) and disables the submit button, but does not provide any other visual indication or instructions to the user that they should not try to work on the task.

**Comment by cash** [comment]
#105 fixes this
